### ISSUE TITLE
Bad Shell alias 

### ISSUE THREAD

**Issue by mazinbokhari** [macmade/trash#2]
Your shell alias is quite dangerous

**Comment by macmade** [comment]
Closing for now...
Maybe try to elaborate a bit when posting issues.

**Comment by mazinbokhari** [comment]
Sorry, should've explained my thoughts. I think aliasing rm to trash is dangerous just because you might be working on another system (e.g. coworkers, fresh install, remote) without the application and/or alias without realizing it. Probably better to just have a separate alias.
