### ISSUE TITLE
Tested on Catalina? 

### ISSUE THREAD

**Issue by ghost** [macmade/trash#4]
If you've tested this on macOS 10.15 and confirm it works well for development with `git` please drop a line or emoji bomb here so we know. Thanks!

**Comment by macmade** [comment]
What do you mean with «development with git»?

**Comment by macmade** [comment]
Closing as no answer...

**Comment by ghost** [comment]
Can this be installed via command line using Nix, Brew Cask or should we pull from source using git?

**Comment by macmade** [comment]
**Maybe you should start by reading the readme file**...  
By the way it's displayed on the project's home page...

**Comment by ghost** [comment]
I don't know what you're talking about hombre but I can assure you I won't be touching this software.
